apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-secondary-cluster
spec:
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*
  kafka:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: console-kafka-metrics
    version: 3.8.0
    replicas: 3
    authorization:
      superUsers:
        - ANONYMOUS
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - authentication:
          type: scram-sha-512
        name: extscram
        port: 9094
        tls: true
        type: route
      - authentication:
          type: tls
        name: exttls
        port: 9095
        tls: true
        type: route
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.8"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: console-kafka-metrics
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
