apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: kafka-dcdr-mm2
  namespace: kafka
spec:
  clusters:
    - alias: primary-kafka-cluster
      authentication:
        certificateAndKey:
          certificate: user.crt
          key: user.key
          secretName: primary-cluster-user2
        type: tls
      bootstrapServers: 'kafka-primary-cluster-kafka-exttls-bootstrap-kafka.apps.primary.com:443'
      tls:
        trustedCertificates:
          - pattern: '*.crt'
            secretName: kafka-primary-cluster-cluster-ca-cert
    - alias: secondary-kafka-cluster
      authentication:
        certificateAndKey:
          certificate: user.crt
          key: user.key
          secretName: secondary-cluster-user2
        type: tls
      bootstrapServers: 'kafka-secondary-cluster-kafka-exttls-bootstrap-kafka.apps.secondary.com:443'
      config:
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
      tls:
        trustedCertificates:
          - pattern: '*.crt'
            secretName: kafka-secondary-cluster-cluster-ca-cert
  connectCluster: secondary-kafka-cluster
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: -1
          refresh.groups.interval.seconds: 600
          replication.policy.class: org.apache.kafka.connect.mirror.IdentityReplicationPolicy
          sync.group.offsets.enabled: 'false'
        tasksMax: 1
      groupsPattern: .*
      sourceCluster: primary-kafka-cluster
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: -1
          refresh.topics.interval.seconds: 600
          replication.factor: -1
          replication.policy.class: org.apache.kafka.connect.mirror.IdentityReplicationPolicy
          sync.topic.acls.enabled: 'false'
        tasksMax: 1
      targetCluster: secondary-kafka-cluster
      topicsPattern: .*
  replicas: 1
  version: 3.8.0
