apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
    app.kubernetes.io/part-of: strimzi-kafka-cluster-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "DWH-Kafka-Cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-primary-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: AUTH_TYPE
              value: '"LOGIN_FORM"'
            - name: SPRING_SECURITY_USER_NAME
              value: admin
            - name: SPRING_SECURITY_USER_PASSWORD
              value: admin
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  selector:
    app: kafka-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31006

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafka-ui-service
spec:
  subdomain: kafka-ui-service
  port:
    targetPort: 8080
  to:
    kind: Service
    name: kafka-ui-service